### ISSUE TITLE
Rémi je t'aime.

### ISSUE THREAD

**Issue by ghost** [EmilieCLARY/WorkCIR1#1]
Bonsoir Rémi, comment vas tu depuis 5 minutes ?
J'espere que tu passe une bonne journée.
Cordialement, l'administration de Promo 67,5.
![Test 2](https://user-images.githubusercontent.com/85520924/150979925-7dc111da-514a-4909-a56e-b6a622962c0d.svg)

**Comment by remivanboxem** [comment]
Bonjour @Siryak, je me permets juste de rappeler que ce dépôt est publique. Je pense qu'Émilie doit nous haïr à être spam de message haha.
Mais merci pour ton message d'amour <3
Content de voir que je ne te harcèle pas x)
